Chef/Deprecations/FoodcriticFile:
  Enabled: false
Chef/Modernize/DefinesChefSpecMatchers:
  Enabled: false
ClassAndModuleChildren:
  Enabled: false
Encoding:
  Enabled: false
Layout/ParameterAlignment:
  Enabled: false
LineLength:
  Max: 200
NumericLiterals:
  Enabled: false
HashSyntax:
  Enabled: false
Metrics/BlockLength:
  Max: 50
#   EnforcedStyle: hash_rockets
AllCops:
  Exclude:
    - Rakefile
    - Gemfile
    - Guardfile
    - Vagrantfile
    - metadata.rb
    - spec/**/*
    - vendor/**/*
