name             'managed_directory'
maintainer       'Zachary Stevens'
maintainer_email 'zts@cryptocracy.com'
license          'Apache 2.0'
description      'Provides the managed_directory resource'
long_description IO.read(File.join(File.dirname(__FILE__), 'README.md'))
source_url       'https://github.com/zts/chef-cookbook-managed_directory'
issues_url       'https://github.com/zts/chef-cookbook-managed_directory/issues'
supports         'centos'
supports         'redhat'
supports         'mac_os_x'
chef_version     '>= 12.5'
version          '0.3.1'
